class Constants
  TOP5_REPORT = 'top5'
  REPORT_TYPES = [TOP5_REPORT];
  
  TOP_5_FILE = 'top5'
  GUIDELINESS_FILE = 'guidelines'
  DILUTION_FILE = 'dilution'
  BATCH_FILE = 'batch'
  PEERS_FILE = 'peers'
  BOD_FILE = 'bod'

  FILE_TYPES = [TOP_5_FILE, GUIDELINESS_FILE, DILUTION_FILE, BATCH_FILE, PEERS_FILE, BOD_FILE]
end