class Constants
  TOP5_REPORT = 'top5'
  BOD_REPORT = 'BOD'
  REPORT_TYPES = [TOP5_REPORT, BOD_REPORT];
  
  TOP_5_FILE = 'top5'
  GUIDELINESS_FILE = 'guidelines'
  DILUTION_FILE = 'dilution'
  BATCH_FILE_COMPANIES = 'batch_companies'
  BATCH_FILE_BOD = 'batch_bod'
  BATCH_FILE_PEERS = 'batch_peers'
  PEERS_FILE = 'peers'
  BOD_FILE = 'bod'

  FILE_TYPES = [TOP_5_FILE, GUIDELINESS_FILE, DILUTION_FILE, BATCH_FILE_COMPANIES, BATCH_FILE_BOD, BATCH_FILE_PEERS, PEERS_FILE, BOD_FILE]
end