source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'bootstrap-sass', '~> 2.3.1.0'

gem 'sqlite3'
gem 'jquery-rails'
gem 'devise'
gem 'pg'
gem 'cancan'
gem 'annotate'
gem 'activeadmin'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'therubyracer', platforms: :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  # Debugging
  gem 'pry'
  gem 'debugger'
  gem 'debugger-pry'
  gem 'pry-nav'
  gem 'pry-stack_explorer'

  # Testing
  gem 'spork-rails'
  gem 'timecop'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner'
end