source 'https://rubygems.org'

gem 'rails', '3.2.12'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'devise'
gem 'pg'
gem 'cancan'
gem 'annotate'
gem 'inherited_resources'
gem 'rest-client'
gem 'kaminari'
gem 'american_date'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', platforms: :ruby
  gem 'uglifier', '>= 1.0.3'
  # foundation
  gem 'compass-rails' # you need this or you get an err
  gem 'zurb-foundation', '~> 4.0.0'
end

group :test, :development, :integration do
  gem 'pry'
  gem 'debugger'
  gem 'debugger-pry'
  gem 'pry-nav'
  gem 'pry-stack_explorer'
end

group :test, :integration do
  gem 'spork-rails'
  gem 'timecop'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner'
  gem 'cucumber-rails', require: false
  gem 'capybara'
end

group :integration do
  gem 'sqlite3'
end
